### ISSUE TITLE
jquery.keypad.js:436 Uncaught TypeError: Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by lyongdee** [kbwood/keypad#9]
When using $(selector).keypad('show') to  pop up the keypad for the given field, there is an error
![image](https://user-images.githubusercontent.com/369124/76351997-4cc59100-6349-11ea-97b3-9a4cf3d1c668.png)

**Comment by kbwood** [comment]
Has the field been initialised with the keypad plugin first? Can you provide a page that shows the problem?

**Comment by lyongdee** [comment]
Thanks, It's OK. The filed must be initialized with the kepad plugin.
